{
    'name': "Fisa Buffet",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'license': 'LGPL-3',
    'version': '15.0.1.0.2',
    'depends': ['base', 'sale', 'stock','mrp','mail'],
    'data': ['security/ir.model.access.csv',
             'security/security.xml',
             'data/removing_tray_cron.xml',
             'data/email_notification.xml',
             'views/sequance.xml',
             'views/buffet_transfer.xml',
             'views/buffet_view.xml',
             'views/menu_type.xml',
             'views/buffet_menu_item.xml',
             'views/buffet_kitchen.xml',
             'views/refill_order.xml',
             'views/tray_view.xml',
             'views/product_tray.xml',
             'views/stock_move_line_tay.xml',
             'views/tray_manufacture.xml',
             'views/removing_request.xml',
             'views/product.xml',
             'views/buffet_details.xml',
             'views/scrap_tray.xml',

             ],

    'images': ['static/description/buffet-management-v15-banner.png'],

    'installable': True,
    'application': True,
    'auto_install': False,
}
